# Generated by Django 5.2.5 on 2025-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_lesson_description_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outcome',
            field=models.TextField(blank=True, help_text='Что студент сможет после прохождения курса', null=True),
        ),
    ]
