# Generated by Django 5.2.5 on 2025-09-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый')], default=1, verbose_name='Уровень сложности'),
        ),
    ]
