# Generated by Django 5.2.5 on 2025-10-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_achievement_studentachievement_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
